import { StyleSheet } from 'react-native';
import { radius, space, stroke, type } from '../../theme/tokens';

export const styles = StyleSheet.create({
  container: { flex: 1 },

  sectionLabel: {
    ...type.section,
    marginBottom: space[2],
    marginTop: space[1],
    marginLeft: 2,
  },

  card: {
    borderRadius: radius.lg,
    padding: space[4],
    marginBottom: space[3],
    borderWidth: stroke.width,
    overflow: 'hidden',
  },
  cardAccent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
    borderTopLeftRadius: radius.lg,
    borderBottomLeftRadius: radius.lg,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: space[2],
    gap: space[2],
  },
  cardTitleRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  typeIcon: {
    width: 28,
    height: 28,
    borderRadius: radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardName: { fontSize: 15, fontWeight: '600', flex: 1 },
  statusPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: radius.sm,
  },
  cardStatus: { fontSize: 11, fontWeight: '600' },
  cardAmount: {
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: -0.4,
    marginBottom: space[2],
  },
  cardMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: space[2],
  },
  cardDate: { fontSize: 13 },
  cardDaysLeft: { fontSize: 12, fontWeight: '600' },
  cardAccountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: radius.md,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderWidth: stroke.width,
    alignSelf: 'flex-start',
    marginBottom: 6,
  },
  cardAccount: { fontSize: 12 },
  cardSource: { fontSize: 13, marginTop: 2 },
  cardNotes: { fontSize: 13, fontStyle: 'italic', marginTop: 4, lineHeight: 18 },
  cardActions: {
    flexDirection: 'row',
    marginTop: space[3],
    gap: 10,
    alignItems: 'center',
    paddingTop: space[3],
    borderTopWidth: stroke.width,
  },
  btnConfirm: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 4,
  },
  btnCancel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 4,
  },
  btnEdit: {
    marginLeft: 'auto',
    borderRadius: radius.md,
    borderWidth: stroke.width,
    padding: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnDelete: {
    marginLeft: 'auto',
    borderRadius: radius.md,
    borderWidth: stroke.width,
    padding: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnText: { fontSize: 13, fontWeight: '600' },

  emptyState: { alignItems: 'center', paddingVertical: 72, paddingHorizontal: 28 },
  emptyIconWrap: {
    width: 72,
    height: 72,
    borderRadius: radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  emptyTitle: { fontSize: 18, fontWeight: '700', marginTop: 16 },
  emptySubtitle: { fontSize: 14, textAlign: 'center', marginTop: 8, lineHeight: 20 },

  fab: {
    position: 'absolute', right: 20, bottom: 90,
    borderRadius: radius.fab, width: 56, height: 56,
    alignItems: 'center', justifyContent: 'center',
    elevation: 6,
    shadowColor: '#000',
    shadowOpacity: 0.28,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },

  modalOverlay: { flex: 1, justifyContent: 'flex-end' },
  modalCard: {
    borderTopLeftRadius: radius.sheet, borderTopRightRadius: radius.sheet,
    padding: space[5], maxHeight: '92%',
  },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  typeToggleRow: {
    flexDirection: 'row', borderRadius: radius.md, borderWidth: stroke.width,
    overflow: 'hidden', marginBottom: 16,
  },
  typeBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 10 },
  typeBtnText: { fontSize: 14, fontWeight: '600' },
  modalTitle: { fontSize: 18, fontWeight: '700' },
  label: { fontSize: 13, marginBottom: 6, marginTop: 12 },
  input: {
    borderRadius: radius.md, padding: 12, fontSize: 15, borderWidth: stroke.width,
  },
  amountRow: { flexDirection: 'row', gap: 8 },
  currencyBtn: { borderRadius: radius.md, paddingHorizontal: 16, justifyContent: 'center' },
  currencyText: { fontWeight: '700' },
  accountBtn: {
    borderRadius: radius.md, paddingHorizontal: 14,
    paddingVertical: 8, marginRight: 8, borderWidth: stroke.width,
  },
  accountBtnText: { fontSize: 14 },
  recurrenceRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  recBtn: {
    borderRadius: radius.md, paddingHorizontal: 12, paddingVertical: 6,
    borderWidth: stroke.width,
  },
  recBtnText: { fontSize: 13 },
  addBtn: {
    borderRadius: radius.md,
    paddingVertical: 14,
    alignItems: 'center',
    minHeight: 48,
    maxHeight: 52,
  },
});
